### ISSUE TITLE
Error on `vimwiki convert` when an output directory is missing

### ISSUE THREAD

**Issue by brennen** [chipsenkbeil/vimwiki-rs#115]
With vimwiki-cli built from ccd3119. On first running convert, I was getting this:

```
21:56:36 brennen@inertia:~/notes (master *$%>) ✮ vimwiki convert ~/notes/vimwiki/index.wiki         
ERROR - Failed to load vimwiki_list from vim/neovim: invalid value: string "/home/brennen/notes/markdownwiki/html/", expected No such file or directory (os error 2)
```

Took me a minute to realize that it probably just wanted `~/notes/markdownwiki/html` (as specified in config) to exist.

**Comment by chipsenkbeil** [comment]
@brennen, it's supposed to create that directory for you, but I think I have a check floating somewhere that tries to canonicalize the path when first being fed in and it's probably failing as you said. Let me see if I can check in a fix in a little bit.

Migrating some internal code over to https://github.com/chipsenkbeil/vimvar-rs

**Comment by chipsenkbeil** [comment]
@brennen, see if https://github.com/chipsenkbeil/vimwiki-rs/commit/5443ff17c8416d6534fa33d088db309667326f42 fixes the issue.

**Comment by brennen** [comment]
No longer fails if `~/notes/markdownwiki/html` doesn't exist, but I'm also not sure if it's finding the config for that wiki. Can't get it to produce output for `~/notes/markdownwiki/index.md` at all.

**Comment by chipsenkbeil** [comment]
@brennen, what do you see for `vimwiki convert -vvvv` at the beginning with regard to `g:vimwiki_list`? Should reflect what it has read there.

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/2481802/120125255-a51ac580-c17d-11eb-8227-d351ff60d569.png">

**Comment by brennen** [comment]
```
21:39:15 brennen@inertia:~/code/chipsenkbeil/vimwiki-rs (master=) ✾ vimwiki convert -vvvv
TRACE - load_html_config(path = None, include = [], merge = false, extra_paths = [])
TRACE - load_vimwiki_list()
TRACE - g:vimwiki_list == Some(Array([Object({"path_html": String("~/workspace/notes-html/"), "auto_tags": Number(1), "name": String("markdownwiki"), "automatic_nested_syntaxes": Number(1), "auto_diary_index": Number(1), "path": String("~/notes/vimwiki/")}), Object({"path_html": String("~/notes/markdownwiki/html/"), "auto_tags": Number(1), "path": String("~/notes/markdownwiki"), "ext": String(".md"), "automatic_nested_syntaxes": Number(1), "auto_diary_index": Number(1), "syntax": String("markdown")})]))
TRACE - load_ast(_, include = [], cache = "/home/brennen/.cache/vimwiki-cli", no_cache = false, no_prune_cache = false)
DEBUG - Loading wiki @ index = 0 | name = Some("markdownwiki") from "/home/brennen/notes/vimwiki"
```

**Comment by chipsenkbeil** [comment]
Oh, wait, I just realized that you said it's for markdown files. This doesn't support markdown files right now. Only vimwiki syntax.

Additionally, the default extension is ".wiki", which wasn't changed from your config; so, it's skipping all of the markdown files regardless.

You could set ext = ".md" and it would try to parse the files, but would then fail.

**Comment by brennen** [comment]
> Oh, wait, I just realized that you said it's for markdown files. This doesn't support markdown files right now. Only vimwiki syntax.

D'oh, yep. I didn't have any expectations that it _would_ support Markdown, but I think I bounced into assuming it would do something here from the original error caused by the missing dir for that wiki without passing through the "that's markdown" segment of reality.  Not at my sharpest this weekend.

**Comment by chipsenkbeil** [comment]
@brennen it should try to process as vimwiki if the extension is set to the files.

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/2481802/120141069-61d24e00-c1a1-11eb-887f-0df45d616c9a.png">

<img width="802" alt="image" src="https://user-images.githubusercontent.com/2481802/120141104-744c8780-c1a1-11eb-9a19-c1a57dbb0eb4.png">

**Comment by chipsenkbeil** [comment]
Might be worth a separate issue if you're not seeing your wiki that has the extension set to markdown actually attempt to process the files.
