### ISSUE TITLE
Identical IDs for div and headers

### ISSUE THREAD

**Issue by brennen** [chipsenkbeil/vimwiki-rs#117]
At ccd3119.  Noting in case this isn't an intentional reproduction of the vimscript bug described in [vimwiki#486](https://github.com/vimwiki/vimwiki/issues/486).

In:

```vimwiki
= completion =
```

Out:

```html
<div id="completion"><h1 id="completion" class="header">
```

**Comment by chipsenkbeil** [comment]
Yeah, I just did a verbatim logic transfer from the vimwiki plugin's html
logic, not really knowing what it was doing other than making a unique id. I
could do something like make a unique id at the time via a uuid or something.
Thoughts on how to tackle this?

**Comment by brennen** [comment]
My first thought is that I'm not entirely sure what that `<div>` is even _for_. There are styles applied to the `<h1>` in the default stylesheet, but the div literally just wraps the header and isn't styled.  Maybe we should get rid of it upstream as well as here.

(I could be missing something.)

**Comment by chipsenkbeil** [comment]
I'm certainly a fan of diverging from the plugin to produce cleaner html. The
extra div was one of the more confusing aspects to me.

**Comment by chipsenkbeil** [comment]
@brennen what is your opinion for removing the div entirely? Would solve a lot of headaches.

**Comment by brennen** [comment]
I think I'm for it, but I did a bit of digging and I have a theory as to its origins.  If you look at `:help vimwiki-syntax-headers`, there's a bit that says:

```
You can center your headers in HTML by placing spaces before the first '=':
                     = Centered Header L1 =
```

First I've ever noticed it, but I tried this:

```
                      = Centered Header =

The above is supposed to be centered.
```

And with the vimscript html conversion, I get:

```
<div id="Centered Header"><h1 id="Centered Header" class="header"><a href="#Centered Header" class="justcenter">Centered Header</a></h1></div>

<p>
The above is supposed to be centered.
</p>
```

This doesn't actually _work_, since centering the text within the `<a>` tag isn't going to do much, but if you look at the [history for the relevant code](https://github.com/vimwiki/vimwiki/blame/master/autoload/vimwiki/html.vim#L1121), I suspect that maybe the bit that adds the class:

```vim
    if centered
      let h_part .= ' class="justcenter">'
    else
      let h_part .= '>'
    endif
```

...originally would have added it to the div rather than the link.

I lean towards just getting rid of it both here and in the plugin. It doesn't look fun, but maybe I can tackle cleaning up `process_tag_para()` in `autoload/vimwiki/html.vim`.

**Comment by chipsenkbeil** [comment]
> I lean towards just getting rid of it both here and in the plugin. It doesn't look fun, but maybe I can tackle cleaning up process_tag_para() in autoload/vimwiki/html.vim.

@brennen the html output on dev branch is broken in several places, so I feel for you. I would have assumed there were tests to cover html output - and I think there are - but they seem to have missed some of the breakage. Personally, I've not viewed the html vimscript support as worth maintaining, but it's impossible to tell what kind of impact it would have to remove it. That and there isn't another option that supports it (yet) at the level that the plugin tried to accomplish.

**Comment by brennen** [comment]
I just went back and read the thread on https://github.com/vimwiki/vimwiki/issues/486#issuecomment-390315975 where @EinfachToll says:

> There are two ways to make a link to an anchor in Vimwiki: [file#anchor] and [file#header1#header2#anchor], where you provide the complete header hierarchy. Because of this, an anchor needs two id's. The div is just a dummy tag so that you can give two id's to one header.

I guess I might need to dig into that a bit further.  I don't know if it's handled in some way by link resolution code...

> Personally, I've not viewed the html vimscript support as worth maintaining, but it's impossible to tell what kind of impact it would have to remove it. That and there isn't another option that supports it (yet) at the level that the plugin tried to accomplish.

Yeah, it's tricky.  I don't really feel comfortable pushing to remove it, but it's a gnarly chunk of code that happens to define a lot of the expected behavior, and refactoring it feels kind of nightmarish.  Trickier because I mostly use the wiki in-editor and don't _personally_ rely on HTML generation for much, so my guess as to how important it is to retain the vimscript code for this might be skewed. This probably needs more thought than I'm going to usefully give it this time of night on a holiday weekend. :)

**Comment by chipsenkbeil** [comment]
> This probably needs more thought than I'm going to usefully give it this time of night on a holiday weekend. :)

For legacy reasons, I don't think it'll ever be removed unless we cut a v3.0 and have that be a requirement. Unless my project (or another) gets popular enough to be relied upon entirely, it probably shouldn't happen, either. Was more of me voicing thoughts and opinions. 😆 



> >There are two ways to make a link to an anchor in Vimwiki: [file#anchor] and [file#header1#header2#anchor], where you provide the complete header hierarchy. Because of this, an anchor needs two id's. The div is just a dummy tag so that you can give two id's to one header.
>
> I guess I might need to dig into that a bit further. I don't know if it's handled in some way by link resolution code...

Hey, I did a nested blockquote! Anyway, I'd seen and support the `file#header1#header2#anchor` conversion as I translate the additional `#` into `-` just like vimwiki. I guess it makes sense and I can pretty easily check to see if a duplicate would happen.

A separate issue is what happens when you repeat a header with the same name:

```
= header =

= header =

= header =
```

from the plugin, you have even more duplicate ids:

```html
<div id="header"><h1 id="header" class="header"><a href="#header">header</a></h1></div>

<div id="header"><h1 id="header" class="header"><a href="#header">header</a></h1></div>

<div id="header"><h1 id="header" class="header"><a href="#header">header</a></h1></div>
```

I'm going to see how other tools tied to markdown handle repeated headers with ids.

**Comment by chipsenkbeil** [comment]
Also, see this old discussion on hugo, which uses the blackfriday markdown library, about duplicate ids. It starts a little bit into the issue: https://github.com/gohugoio/hugo/pull/591

**Comment by chipsenkbeil** [comment]
@brennen worth seeing how well this new update works. It's based on blackfriday's implementation for markdown.
