### ISSUE TITLE
List items with embedded line breaks render with no space between words on either side of newline

### ISSUE THREAD

**Issue by brennen** [chipsenkbeil/vimwiki-rs#139]
At 26daf289. Noted a regression (I think) while testing #120.

**Input**:

```
  - first item
  - second item, with
    embedded hard line wrapping
```

**Output**:

```html
<ul>
<li>first item</li>
<li>second item, withembedded line wrapping</li>
</ul>
```

**Comment by chipsenkbeil** [comment]
This might have already been a problem. I think I need to rework the list items a little bit, especially since I also need to tackle #81.

**Comment by chipsenkbeil** [comment]
@brennen check out https://github.com/chipsenkbeil/vimwiki-rs/commit/1becee0990034f1a5f0590ea5ce6a9507f06090d to see if it fixes the hard line wrapping. You should see text wrapped in paragraph tags as well as  I updated to mirror how markdown parsers output to html.

**Comment by brennen** [comment]
Yep, fixed!
