### ISSUE TITLE
Standalone in-page anchor links point to index.html rather than current page on conversion

### ISSUE THREAD

**Issue by brennen** [chipsenkbeil/vimwiki-rs#144]
On 8164b4bf.

This is in a `vimwiki-scratchpad.wiki`.

**Input**:

```
  - [[#stuff]]
```

**Output**:

```
<ul>
<li><p><a href="index.html#stuff">#stuff</a></p></li>
…
```

For context, I hardly ever write these by hand, but they show up pretty frequently in the table of contents generated with `:VimwikiTOC`.

**Comment by chipsenkbeil** [comment]
@brennen believe I've fixed this with the latest commit. Give it a whirl when you have time 😄

**Comment by brennen** [comment]
Confirmed fixed. :)
